package models

type User struct {
	ID int `properties:"PRIMARY KEY AUTOINCREMENT"`
	Username string
	Password string
}

func (user User) Create() User {
	// update users id with the autogenerated
	// id from the database
	user.ID = Insert(user)
	
	return user
}